config/routes.rb
Rails.application.routes.draw do
  resources :produces
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produce.rb
class Produce < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produces_controller.rb
class ProducesController < ApplicationController
  before_action :set_produce, only: %i[ show edit update destroy ]

  # GET /produces or /produces.json
  def index
    @produces = Produce.all
  end

  # GET /produces/1 or /produces/1.json
  def show
  end

  # GET /produces/new
  def new
    @produce = Produce.new
  end

  # GET /produces/1/edit
  def edit
  end

  # POST /produces or /produces.json
  def create
    @produce = Produce.new(produce_params)

    respond_to do |format|
      if @produce.save
        format.html { redirect_to produce_url(@produce), notice: "Produce was successfully created." }
        format.json { render :show, status: :created, location: @produce }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produces/1 or /produces/1.json
  def update
    respond_to do |format|
      if @produce.update(produce_params)
        format.html { redirect_to produce_url(@produce), notice: "Produce was successfully updated." }
        format.json { render :show, status: :ok, location: @produce }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produces/1 or /produces/1.json
  def destroy
    @produce.destroy

    respond_to do |format|
      format.html { redirect_to produces_url, notice: "Produce was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produce
      @produce = Produce.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produce_params
      params.require(:produce).permit(:name, :price, :vendor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produces_helper.rb
module ProducesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductRegister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produces/_form.html.erb
<%= form_with(model: produce, local: true) do |form| %>
  <% if produce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produce.errors.count, "error") %> prohibited this produce from being saved:</h2>

      <ul>
      <% produce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produces/edit.html.erb
<h1>Editing Produce</h1>

<%= render 'form', produce: @produce %>

<%= link_to 'Show', @produce %> |
<%= link_to 'Back', produces_path %>

app/views/produces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produces.each do |produce| %>
      <tr>
        <td><%= produce.name %></td>
        <td><%= produce.price %></td>
        <td><%= produce.vendor %></td>
        <td><%= link_to 'Show', produce %></td>
        <td><%= link_to 'Edit', edit_produce_path(produce) %></td>
        <td><%= link_to 'Destroy', produce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produce', new_produce_path %>

app/views/produces/new.html.erb
<h1>New Produce</h1>

<%= render 'form', produce: @produce %>

<%= link_to 'Back', produces_path %>

app/views/produces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @produce.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @produce.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @produce.vendor %>
</p>

<%= link_to 'Edit', edit_produce_path(@produce) %> |
<%= link_to 'Back', produces_path %>